// Domaines d'adresses jetables les plus courants (FR et international).
// Liste volontairement courte : à compléter si des abus apparaissent.
const DISPOSABLE_DOMAINS = new Set([
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "burnermail.io",
  "byom.de",
  "cool.fr.nf",
  "courriel.fr.nf",
  "discard.email",
  "dispostable.com",
  "emailondeck.com",
  "fakeinbox.com",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "jetable.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "mail-temporaire.fr",
  "mailcatch.com",
  "maildrop.cc",
  "mailinator.com",
  "mailinator.net",
  "mailnesia.com",
  "mailpoof.com",
  "mintemail.com",
  "moakt.com",
  "mohmal.com",
  "monemail.fr.nf",
  "moncourrier.fr.nf",
  "monmail.fr.nf",
  "mytemp.email",
  "nada.email",
  "nospam.ze.tc",
  "sharklasers.com",
  "spam4.me",
  "spamgourmet.com",
  "speed.1s.fr",
  "temp-mail.io",
  "temp-mail.org",
  "tempail.com",
  "tempmail.com",
  "tempmail.net",
  "tempmailo.com",
  "tempr.email",
  "throwawaymail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@").pop()?.toLowerCase() ?? "";
  return DISPOSABLE_DOMAINS.has(domain);
}
