-- V2 · Contenu de départ : réglages et plans, bibliothèque de principes, quêtes, succès, fonds, départ collectif.

insert into public.settings (key, value) values
  ('audit_rate', '0.10'),
  -- Montants en centimes. Les identifiants des prix Stripe sont renseignés après la création des prix.
  ('plans', '{
    "arc": {"once": {"amount": 1999, "price_id": null}},
    "pro": {"month": {"amount": 1499, "price_id": null}, "year": {"amount": 9999, "price_id": null}},
    "fondateur": {"lifetime": {"amount": 19900, "price_id": null}, "limit": 100}
  }');

-- ---------------------------------------------------------------------------
-- Bibliothèque de principes. Chaque gabarit dit pourquoi il marche et d'où il vient.
-- goal_types / weak_points : pour qui il est proposé en priorité.
-- ---------------------------------------------------------------------------
insert into public.principle_templates
  (code, pillar, goal_types, weak_points, categories, if_text, then_text, proof_type, difficulty, days, target, why, source, sort)
values
  -- Énergie
  ('reveil_fixe', 'energie', '{}', '{reveil,regularite}', '{etudes,business,mixte}',
    'S''il est 7 h', 'alors je me lève et j''ouvre Nonante', 'reveil', 2, '{1,2,3,4,5,6,7}', '{"before":"07:00"}',
    'Se lever à heure fixe, même le week-end, règle l''horloge interne : plus d''énergie, moins de volonté gaspillée.',
    'Chronobiologie, régularité du sommeil', 1),
  ('telephone_dehors', 'energie', '{}', '{telephone,reveil}', '{etudes,business,mixte}',
    'S''il est 22 h 30', 'alors mon téléphone dort hors de ma chambre', 'photo', 1, '{1,2,3,4,5,6,7}', '{"after":"22:30"}',
    'Le téléphone au lit vole des heures de sommeil et la première heure du matin.',
    'Hygiène du sommeil', 2),
  ('lumiere_matin', 'energie', '{}', '{reveil}', '{etudes,business,mixte}',
    'Si je me lève', 'alors 10 minutes dehors à la lumière du jour, avant tout écran', 'declaratif', 1, '{1,2,3,4,5,6,7}', '{}',
    'La lumière du matin cale l''horloge interne et réveille mieux que le café.',
    'Chronobiologie', 3),
  ('eau_reveil', 'energie', '{}', '{regularite}', '{etudes,business,mixte}',
    'Si je sors du lit', 'alors un grand verre d''eau avant le café', 'declaratif', 1, '{1,2,3,4,5,6,7}', '{}',
    'Accrocher une nouvelle habitude à un geste déjà automatique la rend presque gratuite.',
    'Empilement d''habitudes (BJ Fogg, James Clear)', 4),
  ('zero_soda', 'energie', '{corps}', '{}', '{etudes,business,mixte}',
    'Si j''ai soif', 'alors de l''eau, jamais de soda ni de boisson énergisante', 'declaratif', 1, '{1,2,3,4,5,6,7}', '{}',
    'Le sucre liquide donne un pic d''énergie, puis une chute : tu travailles moins bien deux heures plus tard.',
    'Nutrition', 5),

  -- Focus
  ('bloc_profond', 'focus', '{}', '{telephone,procrastination,dispersion}', '{etudes,business,mixte}',
    'Si je m''assois à mon bureau', 'alors {minutes} minutes de travail profond, téléphone dans une autre pièce', 'session', 2,
    '{1,2,3,4,5,6,7}', '{"minutes":50}',
    'Une seule tâche exigeante, sans interruption : c''est là que se fait le travail qui compte.',
    'Cal Newport, Deep Work', 10),
  ('grenouille', 'focus', '{lancement,examens,revenu}', '{procrastination}', '{etudes,business,mixte}',
    'Si ma journée commence', 'alors ma tâche la plus difficile en premier, finie avant midi', 'session', 2,
    '{1,2,3,4,5}', '{"minutes":50,"before":"12:00"}',
    'Commencer par le plus dur enlève le poids qui gâche le reste de la journée.',
    'Brian Tracy, Eat That Frog!', 11),
  ('fatigue_25', 'focus', '{}', '{procrastination,regularite}', '{etudes,business,mixte}',
    'Si je suis fatigué', 'alors 25 minutes au lieu de rien', 'session', 1, '{1,2,3,4,5,6,7}', '{"minutes":25}',
    'Un petit bloc vaut mieux que zéro : la série continue, la discipline aussi.',
    'Francesco Cirillo, technique Pomodoro', 12),
  ('deux_minutes', 'focus', '{}', '{procrastination,dispersion}', '{etudes,business,mixte}',
    'Si je ne sais pas par où commencer', 'alors j''écris la plus petite action possible et je la fais tout de suite',
    'declaratif', 1, '{1,2,3,4,5,6,7}', '{}',
    'Démarrer est le plus dur. Une action minuscule casse l''inertie.',
    'Règle des 2 minutes (David Allen, James Clear)', 13),
  ('une_priorite', 'focus', '{}', '{dispersion}', '{etudes,business,mixte}',
    'Si ma journée se termine', 'alors j''écris la seule priorité de demain, sur papier', 'photo', 1, '{1,2,3,4,5,6,7}',
    '{"after":"18:00"}',
    'Une priorité décidée la veille, c''est une matinée sans hésitation.',
    'Méthode Ivy Lee, Gary Keller (The ONE Thing)', 14),
  ('weekend_90', 'focus', '{lancement,examens}', '{regularite}', '{etudes,business,mixte}',
    'Si c''est le week-end', 'alors ma session la plus longue, finie avant midi', 'session', 3, '{6,7}',
    '{"minutes":90,"before":"12:00"}',
    'Le week-end, les autres décrochent. C''est là que tu prends de l''avance.',
    'Cal Newport, Deep Work', 15),
  ('revue_dimanche', 'focus', '{}', '{dispersion}', '{etudes,business,mixte}',
    'Si c''est dimanche soir', 'alors je planifie ma semaine bloc par bloc', 'photo', 2, '{7}', '{"after":"17:00"}',
    'Une semaine planifiée se subit moins : chaque bloc a déjà sa place.',
    'Revue hebdomadaire (David Allen, Getting Things Done)', 16),
  ('reseaux_midi', 'focus', '{}', '{telephone}', '{etudes,business,mixte}',
    'Si je me réveille', 'alors aucun réseau social avant midi', 'declaratif', 2, '{1,2,3,4,5,6,7}', '{}',
    'Le matin, ton attention est à son meilleur. Ne la donne pas aux autres.',
    'Cal Newport, Digital Minimalism', 17),
  ('revision_active', 'focus', '{examens}', '{}', '{etudes,mixte}',
    'Si j''ai un examen dans le mois', 'alors 50 minutes d''exercices et d''annales, pas de relecture', 'session', 2,
    '{1,2,3,4,5,6}', '{"minutes":50}',
    'Se tester fait mieux retenir que relire : c''est l''effet de test.',
    'Roediger et Karpicke, pratique de récupération', 18),
  ('devoir_jour_meme', 'focus', '{examens}', '{procrastination}', '{etudes,mixte}',
    'Si on me donne un devoir', 'alors je le commence le jour même', 'declaratif', 2, '{1,2,3,4,5,6,7}', '{}',
    'Commencer tôt, même un peu, enlève l''urgence de la dernière nuit.',
    'Lutte contre la procrastination', 19),

  -- Business
  ('prospection', 'business', '{revenu,clients}', '{vente}', '{business,mixte}',
    'Si c''est un jour de semaine', 'alors 20 messages à des clients potentiels', 'capture', 2, '{1,2,3,4,5}',
    '{"count":20,"unit":"messages"}',
    'Le volume d''abord : plus de messages, plus de conversations, plus de ventes.',
    'Alex Hormozi, la règle des 100 ($100M Leads)', 20),
  ('appel_prospect', 'business', '{clients,revenu}', '{vente}', '{business,mixte}',
    'Si j''ai envoyé mes messages', 'alors un appel ou un rendez-vous avec un prospect', 'declaratif', 2, '{1,2,3,4,5}', '{}',
    'Une vraie conversation vaut cent messages : c''est là qu''on comprend et qu''on vend.',
    'Vente consultative', 21),
  ('relance', 'business', '{clients,revenu}', '{vente}', '{business,mixte}',
    'Si un prospect n''a pas répondu depuis 3 jours', 'alors je le relance', 'declaratif', 1, '{1,2,3,4,5}', '{}',
    'Beaucoup de ventes se font à la relance, que la plupart des gens n''envoient jamais.',
    'Relance systématique', 22),
  ('demander_vente', 'business', '{revenu,clients}', '{vente}', '{business,mixte}',
    'Si un prospect hésite', 'alors je lui demande clairement sa décision', 'declaratif', 1, '{1,2,3,4,5}', '{}',
    'Sans demande, pas de vente. Un non clair vaut mieux qu''un peut-être.',
    'Closing : demander la décision', 23),
  ('publier_contenu', 'business', '{audience,lancement}', '{regularite}', '{etudes,business,mixte}',
    'Si c''est lundi, mercredi ou vendredi', 'alors je publie un contenu sur mon projet', 'lien', 2, '{1,3,5}', '{}',
    'Montrer ce que tu construis attire clients, partenaires et opportunités.',
    'Construire en public', 24),
  ('contenu_quotidien', 'business', '{audience}', '{regularite}', '{etudes,business,mixte}',
    'Si c''est un jour de semaine', 'alors un contenu publié, même imparfait', 'lien', 2, '{1,2,3,4,5}', '{}',
    'La régularité bat la perfection : l''audience récompense ceux qui reviennent.',
    'Création de contenu', 25),
  ('livrer', 'business', '{lancement}', '{procrastination,dispersion}', '{etudes,business,mixte}',
    'Si je travaille sur mon produit', 'alors 90 minutes pour livrer une chose visible', 'session', 3, '{1,2,3,4,5}',
    '{"minutes":90}',
    'Livrer souvent, même petit, bat le projet parfait qui ne sort jamais.',
    'Méthodes agiles : livrer en continu', 26),
  ('chiffres_jour', 'business', '{revenu,audience,clients}', '{dispersion}', '{business,mixte}',
    'S''il est 20 h', 'alors je note mes chiffres du jour : ventes, prospects, abonnés', 'capture', 1, '{1,2,3,4,5}', '{}',
    'Regarder ses chiffres chaque jour oblige à voir ce qui marche vraiment.',
    'Tableau de bord du fondateur', 27),
  ('revue_revenus', 'business', '{revenu}', '{}', '{business,mixte}',
    'Si c''est vendredi', 'alors je fais le bilan de mes revenus de la semaine dans mon portefeuille', 'declaratif', 1,
    '{5}', '{}',
    'Un bilan chaque semaine montre la tendance avant qu''il soit trop tard.',
    'Revue hebdomadaire', 28),
  ('offre', 'business', '{revenu,clients,lancement}', '{vente}', '{business,mixte}',
    'Si c''est lundi', 'alors je reformule mon offre en une phrase et je la teste sur une personne', 'declaratif', 1,
    '{1}', '{}',
    'Une offre claire se vend. Une offre floue s''explique.',
    'Alex Hormozi, $100M Offers', 29),

  -- Corps
  ('pompes', 'corps', '{corps}', '{sport}', '{etudes,business,mixte}',
    'Si je sors du lit', 'alors {reps} pompes', 'reps', 2, '{1,2,3,4,5,6,7}', '{"exercise":"pushup","reps":20}',
    'Bouger dès le réveil allume le corps et lance la journée par une victoire.',
    'Exercice matinal', 30),
  ('squats', 'corps', '{corps}', '{sport}', '{etudes,business,mixte}',
    'Si je sors du lit', 'alors {reps} squats', 'reps', 1, '{1,2,3,4,5,6,7}', '{"exercise":"squat","reps":20}',
    'Les plus grands muscles du corps, réveillés en deux minutes.',
    'Exercice matinal', 31),
  ('salle', 'corps', '{corps}', '{sport}', '{etudes,business,mixte}',
    'Si c''est lundi, mercredi ou vendredi', 'alors je vais à la salle et je la prends en photo', 'photo', 2, '{1,3,5}', '{}',
    'Le sport régulier améliore la concentration, l''humeur et le sommeil.',
    'Activité physique et cognition', 32),
  ('marche', 'corps', '{corps}', '{sport}', '{etudes,business,mixte}',
    'Si ma journée se termine', 'alors 8 000 pas, capture de mon compteur', 'capture', 1, '{1,2,3,4,5,6,7}',
    '{"count":8000,"unit":"pas"}',
    'Marcher chaque jour réduit le stress et entretient le cœur, sans fatigue.',
    'Études sur le nombre de pas quotidiens', 33),
  ('course', 'corps', '{corps}', '{sport}', '{etudes,business,mixte}',
    'Si c''est mardi ou samedi', 'alors 30 minutes de course, capture de l''appli', 'capture', 2, '{2,6}', '{}',
    'L''endurance, c''est aussi de la discipline : tu cours même sans en avoir envie.',
    'Endurance', 34),
  ('squats_pause', 'corps', '{}', '{sport}', '{etudes,business,mixte}',
    'Si je finis une session de travail', 'alors {reps} squats pour relancer le corps', 'reps', 1, '{1,2,3,4,5}',
    '{"exercise":"squat","reps":20}',
    'Rester assis toute la journée éteint l''énergie. Deux minutes de mouvement la rallument.',
    'Pauses actives', 35),

  -- Esprit
  ('lecture', 'esprit', '{}', '{telephone}', '{etudes,business,mixte}',
    'Si je me couche', 'alors 10 pages d''un livre, sans écran', 'declaratif', 1, '{1,2,3,4,5,6,7}', '{}',
    'Dix pages par jour, c''est plus d''une dizaine de livres par an.',
    'Lecture quotidienne', 40),
  ('journal', 'esprit', '{}', '{regularite,dispersion}', '{etudes,business,mixte}',
    'Si ma journée se termine', 'alors 3 lignes : ce que j''ai fait, ce que j''ai appris, ce que je change demain', 'photo', 1,
    '{1,2,3,4,5,6,7}', '{"after":"19:00"}',
    'Sénèque passait chaque soir sa journée en revue. On progresse en se regardant faire.',
    'Sénèque, De la colère (l''examen du soir)', 41),
  ('silence', 'esprit', '{}', '{telephone,dispersion}', '{etudes,business,mixte}',
    'Si je commence ma journée', 'alors 10 minutes de silence, sans téléphone', 'declaratif', 1, '{1,2,3,4,5,6,7}', '{}',
    'Quelques minutes de calme entraînent l''attention comme un muscle.',
    'Pleine conscience (Jon Kabat-Zinn)', 42),
  ('apprendre', 'esprit', '{lancement,revenu,clients}', '{}', '{etudes,business,mixte}',
    'Si c''est un jour de semaine', 'alors 25 minutes pour apprendre une compétence de mon projet', 'session', 1,
    '{1,2,3,4,5}', '{"minutes":25}',
    'S''entraîner sur ce qu''on ne sait pas encore faire, c''est ce qui fait progresser.',
    'Anders Ericsson, pratique délibérée', 43),
  ('ce_qui_depend', 'esprit', '{}', '{regularite}', '{etudes,business,mixte}',
    'Si j''ai envie de me plaindre', 'alors je cherche ce qui dépend de moi et je le fais', 'declaratif', 1,
    '{1,2,3,4,5,6,7}', '{}',
    'Ne t''occupe que de ce qui dépend de toi : c''est là qu''est ta force.',
    'Épictète, Manuel', 44),
  ('fiches', 'esprit', '{examens}', '{}', '{etudes,mixte}',
    'Si j''ai fini un chapitre', 'alors une fiche de révision, prise en photo', 'photo', 2, '{1,2,3,4,5,6}', '{}',
    'Résumer avec ses mots oblige à comprendre.',
    'Apprentissage actif', 45);

-- ---------------------------------------------------------------------------
-- Quêtes : 3 par catégorie et par palier au moins, plus les pièges.
-- ---------------------------------------------------------------------------
insert into public.challenges (code, category, level, kind, title, description, proof_type, rule, forced_audit) values
  -- Études
  ('etudes_n1_sessions', 'etudes', 1, 'epreuve', '3 sessions de 90 minutes cette semaine.',
    'Trois fois 90 minutes de travail profond, minuteur à l''appui.', 'session',
    '{"type":"sessions","count":3,"min_minutes":90}', false),
  ('etudes_n1_cinq_heures', 'etudes', 1, 'epreuve', '5 heures de sessions cette semaine.',
    'Additionne tes sessions de concentration jusqu''à 5 heures.', 'session',
    '{"type":"session_minutes","minutes":300}', false),
  ('etudes_n1_fiche', 'etudes', 1, 'epreuve', 'Une fiche de révision complète sur un chapitre.',
    'Prends ta fiche en photo, dans l''app.', 'photo', '{"type":"photo"}', false),
  ('etudes_n1_cinq_verts', 'etudes', 1, 'epreuve', '5 jours verts cette semaine.',
    'Tous tes principes prouvés, cinq jours sur sept.', null, '{"type":"green_days","count":5}', false),
  ('etudes_n2_td', 'etudes', 2, 'epreuve', 'Refais un devoir entier sans la correction.',
    'Prends ta copie en photo, dans l''app.', 'photo', '{"type":"photo"}', false),
  ('etudes_n2_annale', 'etudes', 2, 'epreuve', 'Une annale complète, en temps limité.',
    'Conditions d''examen, puis ta copie en photo.', 'photo', '{"type":"photo"}', false),
  ('etudes_n2_matin', 'etudes', 2, 'epreuve', '4 sessions de 50 minutes finies avant 10 h.',
    'Le matin appartient à ceux qui travaillent.', 'session',
    '{"type":"sessions_before","count":4,"min_minutes":50,"before":"10:00","consecutive":false}', false),
  ('etudes_n2_six_verts', 'etudes', 2, 'epreuve', '6 jours verts cette semaine.',
    'Un seul faux pas autorisé.', null, '{"type":"green_days","count":6}', false),
  ('etudes_n3_dix_heures', 'etudes', 3, 'epreuve', '10 heures de sessions cette semaine.',
    'Additionne tes sessions de concentration jusqu''à 10 heures.', 'session',
    '{"type":"session_minutes","minutes":600}', false),
  ('etudes_n3_cinq_sessions', 'etudes', 3, 'epreuve', '5 sessions de 90 minutes cette semaine.',
    'Cinq fois 90 minutes, sans téléphone.', 'session', '{"type":"sessions","count":5,"min_minutes":90}', false),
  ('etudes_n3_memoire', 'etudes', 3, 'epreuve', 'Le plan d''un chapitre entier, de mémoire.',
    'Écris-le sans notes, puis prends-le en photo.', 'photo', '{"type":"photo"}', false),
  ('etudes_n3_sept_verts', 'etudes', 3, 'epreuve', 'Une semaine parfaite.',
    'Sept jours verts sur sept.', null, '{"type":"green_days","count":7}', false),
  -- Business
  ('business_n1_trois', 'business', 1, 'epreuve', 'Parle à 3 clients potentiels.',
    'De vraies conversations, pas des likes.', 'declaratif', '{"type":"declaratif"}', false),
  ('business_n1_offre', 'business', 1, 'epreuve', 'Ton offre en une phrase, publiée.',
    'Colle le lien de ta publication.', 'lien', '{"type":"links","count":1}', false),
  ('business_n1_dix_messages', 'business', 1, 'epreuve', '10 messages de prospection cette semaine.',
    'Dix personnes qui pourraient payer.', 'declaratif', '{"type":"declaratif"}', false),
  ('business_n1_cinq_verts', 'business', 1, 'epreuve', '5 jours verts cette semaine.',
    'Tous tes principes prouvés, cinq jours sur sept.', null, '{"type":"green_days","count":5}', false),
  ('business_n2_precommande', 'business', 2, 'epreuve', 'Obtiens une précommande ou un premier paiement.',
    'Contrôle obligatoire : prépare ta capture.', 'declaratif', '{"type":"declaratif"}', true),
  ('business_n2_trois_contenus', 'business', 2, 'epreuve', 'Publie 3 contenus cette semaine.',
    'Trois jours différents, un lien par jour.', 'lien', '{"type":"links","count":3}', false),
  ('business_n2_appels', 'business', 2, 'epreuve', '3 appels de découverte avec des clients potentiels.',
    'Écoute plus que tu ne parles.', 'declaratif', '{"type":"declaratif"}', false),
  ('business_n2_six_verts', 'business', 2, 'epreuve', '6 jours verts cette semaine.',
    'Un seul faux pas autorisé.', null, '{"type":"green_days","count":6}', false),
  ('business_n3_cinq_contenus', 'business', 3, 'epreuve', 'Publie 5 contenus en 5 jours.',
    'Cinq jours différents, un lien par jour.', 'lien', '{"type":"links","count":5}', false),
  ('business_n3_dix_clients', 'business', 3, 'epreuve', 'Parle à 10 clients potentiels cette semaine.',
    'Contrôle obligatoire : garde tes échanges.', 'declaratif', '{"type":"declaratif"}', true),
  ('business_n3_page', 'business', 3, 'epreuve', 'Mets en ligne une page de vente qui accepte un paiement.',
    'Colle le lien de ta page.', 'lien', '{"type":"links","count":1}', false),
  ('business_n3_sept_verts', 'business', 3, 'epreuve', 'Une semaine parfaite.',
    'Sept jours verts sur sept.', null, '{"type":"green_days","count":7}', false),
  -- Les deux
  ('mixte_n1_planning', 'mixte', 1, 'epreuve', 'Planifie ta semaine en début de semaine.',
    'Ton planning en photo, dans l''app.', 'photo', '{"type":"photo"}', false),
  ('mixte_n1_sessions', 'mixte', 1, 'epreuve', '3 sessions de 50 minutes cette semaine.',
    'Trois fois 50 minutes sans téléphone.', 'session', '{"type":"sessions","count":3,"min_minutes":50}', false),
  ('mixte_n1_pompes', 'mixte', 1, 'epreuve', '50 pompes dans la semaine, comptées.',
    'Comptées à la caméra, sur ton téléphone.', 'reps', '{"type":"reps","exercise":"pushup","count":50}', false),
  ('mixte_n1_cinq_verts', 'mixte', 1, 'epreuve', '5 jours verts cette semaine.',
    'Tous tes principes prouvés, cinq jours sur sept.', null, '{"type":"green_days","count":5}', false),
  ('mixte_n2_sans_reseaux', 'mixte', 2, 'epreuve', 'Une journée entière sans réseaux sociaux.',
    'De ton réveil à ton coucher.', 'declaratif', '{"type":"declaratif"}', false),
  ('mixte_n2_six_heures', 'mixte', 2, 'epreuve', '6 heures de sessions cette semaine.',
    'Additionne tes sessions de concentration jusqu''à 6 heures.', 'session',
    '{"type":"session_minutes","minutes":360}', false),
  ('mixte_n2_aube', 'mixte', 2, 'epreuve', 'Debout avant 6 h 30, trois fois cette semaine.',
    'Tes réveils prouvés comptent.', 'reveil', '{"type":"wakes","count":3,"before":"06:30"}', false),
  ('mixte_n2_six_verts', 'mixte', 2, 'epreuve', '6 jours verts cette semaine.',
    'Un seul faux pas autorisé.', null, '{"type":"green_days","count":6}', false),
  ('mixte_n3_cent_pompes', 'mixte', 3, 'epreuve', '100 pompes dans la semaine, comptées.',
    'Comptées à la caméra, sur ton téléphone.', 'reps', '{"type":"reps","exercise":"pushup","count":100}', false),
  ('mixte_n3_dix_heures', 'mixte', 3, 'epreuve', '10 heures de sessions cette semaine.',
    'Additionne tes sessions de concentration jusqu''à 10 heures.', 'session',
    '{"type":"session_minutes","minutes":600}', false),
  ('mixte_n3_trois_jours', 'mixte', 3, 'epreuve', 'Trois jours sans réseaux sociaux.',
    'Trois jours entiers. Un contrôle peut tomber.', 'declaratif', '{"type":"declaratif"}', false),
  ('mixte_n3_sept_verts', 'mixte', 3, 'epreuve', 'Une semaine parfaite.',
    'Sept jours verts sur sept.', null, '{"type":"green_days","count":7}', false),
  -- Pièges
  ('piege_vendredi', 'tous', 1, 'piege', 'Le piège du vendredi.',
    'Tous tes principes validés vendredi.', null, '{"type":"green_day","isodow":5}', false),
  ('piege_dimanche', 'tous', 1, 'piege', 'Le piège du dimanche.',
    'Réveil prouvé avant 8 h, dimanche.', 'reveil', '{"type":"wake","isodow":7,"before":"08:00"}', false),
  ('piege_bon_eleve', 'tous', 1, 'piege', 'Le piège du bon élève.',
    'Ta session la plus longue, finie avant 10 h, trois jours de suite.', 'session',
    '{"type":"sessions_before","count":3,"before":"10:00","consecutive":true}', false);

-- ---------------------------------------------------------------------------
-- Succès (une fois par joueur) et fonds de carte qu'ils débloquent
-- ---------------------------------------------------------------------------
insert into public.achievements (code, title, description, points, art_slug, sort) values
  ('premier_vert', 'Premier vert', 'Ton premier jour vert.', 25, 'hokusai-vague', 1),
  ('premiere_semaine_parfaite', 'Semaine parfaite', '7 jours verts d''affilée.', 50, 'mondrian-jetee', 2),
  ('serie_30', 'Trente', '30 jours verts d''affilée.', 150, 'piste', 3),
  ('jamais_deux_fois', 'Jamais deux fois', '30 jours sans rater deux fois de suite le même principe.', 150,
    'hammershoi-strandgade', 4),
  ('aube', 'Aube', '10 réveils prouvés avant 6 h 30.', 100, 'aube', 5),
  ('travail_profond_1', 'Travail profond I', '10 heures de sessions.', 50, null, 6),
  ('travail_profond_2', 'Travail profond II', '50 heures de sessions.', 100, 'bureau-nuit', 7),
  ('travail_profond_3', 'Travail profond III', '100 heures de sessions.', 200, 'malevitch-carre-noir', 8),
  ('mille', 'Mille', '1 000 répétitions comptées à la caméra.', 100, 'halteres', 9),
  ('sans_filet', 'Sans filet', '14 jours verts d''affilée, uniquement des preuves fortes.', 150, 'friedrich-rugen', 10),
  ('controle', 'Contrôlé', '5 contrôles réussis.', 50, null, 11),
  ('mi_parcours', 'Mi-parcours', 'Jour 45, sans aucun jour blanc.', 100, 'route', 12),
  ('arc_tenu', 'Arc tenu', '90 jours tenus.', 0, 'adams-tetons', 13),
  ('premier_euro', 'Premier euro', 'Ton premier revenu prouvé.', 50, 'billets', 14),
  ('cent_euros', 'Cent', '100 € de revenus prouvés.', 75, null, 15),
  ('mille_euros', 'Mille euros', '1 000 € de revenus prouvés.', 150, 'liasse', 16),
  ('dix_mille_euros', 'Dix mille', '10 000 € de revenus prouvés.', 300, 'ville-nuit', 17),
  ('niveau_10', 'Niveau 10', 'Tu as atteint le niveau 10.', 100, 'escalier', 18),
  ('niveau_20', 'Niveau 20', 'Tu as atteint le niveau 20.', 200, 'au-dessus-nuages', 19),
  ('ovr_80', 'Quatre-vingts', 'Une note globale de 80.', 150, 'sommet', 20),
  ('escouade', 'Escouade', 'Tu as rejoint une escouade.', 25, 'oiseaux-fil', 21);

insert into public.art_unlocks (slug, unlock) values
  ('nuit-tours', 'base'),
  ('fenetre', 'base'),
  ('arbre', 'base'),
  ('echecs', 'base'),
  ('friedrich-moine', 'base'),
  ('malevitch-carre-blanc', 'base'),
  ('carnet', 'level:3'),
  ('montre', 'level:5'),
  ('clavier', 'level:8'),
  ('pluie-nuit', 'level:15'),
  ('friedrich-voyageur', 'level:25'),
  ('turner-norham', 'level:30'),
  ('marc-aurele', 'level:40'),
  ('hokusai-vague', 'achievement:premier_vert'),
  ('mondrian-jetee', 'achievement:premiere_semaine_parfaite'),
  ('piste', 'achievement:serie_30'),
  ('hammershoi-strandgade', 'achievement:jamais_deux_fois'),
  ('aube', 'achievement:aube'),
  ('bureau-nuit', 'achievement:travail_profond_2'),
  ('malevitch-carre-noir', 'achievement:travail_profond_3'),
  ('halteres', 'achievement:mille'),
  ('friedrich-rugen', 'achievement:sans_filet'),
  ('route', 'achievement:mi_parcours'),
  ('adams-tetons', 'achievement:arc_tenu'),
  ('billets', 'achievement:premier_euro'),
  ('liasse', 'achievement:mille_euros'),
  ('ville-nuit', 'achievement:dix_mille_euros'),
  ('escalier', 'achievement:niveau_10'),
  ('au-dessus-nuages', 'achievement:niveau_20'),
  ('sommet', 'achievement:ovr_80'),
  ('oiseaux-fil', 'achievement:escouade');

-- ---------------------------------------------------------------------------
-- Départ collectif officiel
-- ---------------------------------------------------------------------------
insert into public.squads (name, description, code, is_public, is_official, start_date) values
  ('Départ du 1er janvier', 'Le départ collectif : jour 1 le 1er janvier 2027, tous ensemble.', 'JANV27', true, true, '2027-01-01');
